"""empty message

Revision ID: 5287754ab1b0
Revises: ea1433eedb4e
Create Date: 2023-12-28 16:52:09.792618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5287754ab1b0'
down_revision = 'ea1433eedb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfc_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfc_card', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
