"""empty message

Revision ID: 654854706757
Revises: 5287754ab1b0
Create Date: 2023-12-28 19:05:33.383883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '654854706757'
down_revision = '5287754ab1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfc_card', schema=None) as batch_op:
        batch_op.drop_index('uid')

    op.drop_table('nfc_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfc_card',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uid', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('nfc_card', schema=None) as batch_op:
        batch_op.create_index('uid', ['uid'], unique=True)

    # ### end Alembic commands ###
