"""empty message

Revision ID: 9d507984d596
Revises: 1056b501e721
Create Date: 2024-01-04 20:51:57.190849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d507984d596'
down_revision = '1056b501e721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_rfid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_rfid', sa.String(length=50), nullable=False))
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_rfid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('no_rfid')

    # ### end Alembic commands ###
