"""empty message

Revision ID: a1fb3a58ae32
Revises: e7c9e83846fe
Create Date: 2024-01-18 19:38:42.991289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1fb3a58ae32'
down_revision = 'e7c9e83846fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photoEvidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_time', sa.DateTime(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('image_data', mysql.MEDIUMBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image_data', mysql.MEDIUMBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('photoEvidence')
    # ### end Alembic commands ###
